{
 "title": "dashboard 1",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_exporter_build_info, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Network traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device != \"lo\", instance = \"$node\"}[1m])",
     "legendFormat": "rx"
    },
    {
     "expr": "-irate(node_network_transmit_bytes_total{device!=\"lo\", instance = \"$node\"}[1m])",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "filesystems",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance = \"$node\"}",
     "legendFormat": "{{device}} - {{mountpoint}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(node_cpu_seconds_total {mode!=\"idle\", instance = \"$node\"} [1m])) without (cpu)) / count(node_cpu_seconds_total{instance = \"$node\"}) without (cpu)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_PageTables_bytes{instance = \"$node\"}",
     "legendFormat": "page tables"
    },
    {
     "expr": "node_memory_Slab_bytes{instance = \"$node\"}",
     "legendFormat": "slab"
    },
    {
     "expr": "( node_memory_MemTotal_bytes{instance=~'$node'} - node_memory_MemFree_bytes{instance=~'$node'} - node_memory_Buffers_bytes{instance=~'$node'} - node_memory_Cached_bytes{instance=~'$node'} - node_memory_SwapCached_bytes{instance=~'$node'} - node_memory_Slab_bytes{instance=~'$node'} - node_memory_PageTables_bytes{instance=~'$node'} - node_memory_VmallocUsed_bytes{instance=~'$node'} ) or ( node_memory_MemTotal{instance=~'$node'} - node_memory_MemFree{instance=~'$node'} - node_memory_Buffers{instance=~'$node'} - node_memory_Cached{instance=~'$node'} - node_memory_SwapCached{instance=~'$node'} - node_memory_Slab{instance=~'$node'} - node_memory_PageTables{instance=~'$node'} - node_memory_VmallocUsed{instance=~'$node'} )",
     "legendFormat": "apps"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance = \"$node\"}",
     "legendFormat": "buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance = \"$node\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance=~'$node'}",
     "legendFormat": "swap cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~'$node'}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "IO read",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance = \"$node\"}[15s])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "IO written",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{instance = \"$node\"}[15s])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "network states",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_tcp_connection_states{instance = \"$node\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Process state",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_processes_state{instance = \"$node\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "total processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_processes_pids{instance = \"$node\"}",
     "legendFormat": "total processes"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance = \"$node\"}",
     "legendFormat": "load1"
    }
   ]
  }
 ]
}