{
 "title": "nginx",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_connections_accepted[1m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(nginx_connections_active[1m])",
     "legendFormat": "active"
    },
    {
     "expr": "rate(nginx_connections_handled[1m])",
     "legendFormat": "handled"
    },
    {
     "expr": "rate(nginx_connections_reading[1m])",
     "legendFormat": "reading"
    },
    {
     "expr": "rate(nginx_connections_writing[1m])",
     "legendFormat": "writing"
    },
    {
     "expr": "rate(nginx_connections_waiting[1m])",
     "legendFormat": "waiting"
    }
   ]
  },
  {
   "title": "chessfracture_http_response_count_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(chessfracture_http_response_count_total[15s])",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "nginx_http_requests_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "nginx_http_requests_total"
    }
   ]
  },
  {
   "title": "chessfracture_http_response_size_bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(chessfracture_http_response_size_bytes[1m])",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "chessfracture_http_response_time_seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(chessfracture_http_response_time_seconds{status=\"200\"}[1m]) * 1000",
     "legendFormat": "quantile = {{quantile}}"
    }
   ]
  }
 ]
}