---
# tasks file for chessfracture-web

- name: install firewalld
  yum:
    name:
      - firewalld
    state: installed

- name: enable firewalld
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: postgres
  include: postgres.yml

- name: django
  include: django.yml

- name: reverse proxy
  include: nginx.yml

- name: prometheus
  include: prometheus.yml

- name: grafana
  include: grafana.yml

  #- meta: flush_handlers

- name: start uwsgi
  service:
    name: uwsgi
    state: started
    enabled: true
