---

- name: add postgres repo
  yum:
    name: https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    #name: https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-centos10-10-2.noarch.rpm
    state: installed

- name: install postgres
  yum:
    name:
      - python-psycopg2
      - postgresql10
      - postgresql10-server
    state: installed

- name: init postgres
  command: /usr/pgsql-10/bin/postgresql-10-setup initdb
  args:
    creates: /var/lib/pgsql/10/data/postgresql.conf

- name: postgresql-10 service
  service:
    name: postgresql-10
    state: started
    enabled: true

#https://github.com/ansible/ansible-examples/blob/master/language_features/postgresql.yml
- name: create db
  postgresql_db:
    name: chessfracture
    encoding: UTF-8
  become_user: postgres

- name: create postgres user
  postgresql_user:
    db: chessfracture
    name: chessfracture
    password: nopasswd
  become_user: postgres

- name: listen any
  lineinfile:
    path: /var/lib/pgsql/10/data/postgresql.conf
    line: "listen_addresses = '*'"
  notify: restart postgresql-10

- name: postgres user connect permissions
  lineinfile:
    path: /var/lib/pgsql/10/data/pg_hba.conf
    line: "{{item}}"
    insertbefore: BOF
  notify: restart postgresql-10
  loop:
    - "host  chessfracture  {{ chessfracture_user }} 0.0.0.0/0 md5"
    - "host  chessfracture  {{ chessfracture_user }} 127.0.0.0/8 md5"
    - "host  chessfracture  {{ chessfracture_user }} ::1/128 md5"

- meta: flush_handlers

- name: open port 5432
  firewalld:
    port: 5432/tcp
    permanent: true
    immediate: true
    state: enabled

