# Generated by Django 2.1 on 2018-08-27 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=20)),
                ('gameid', models.CharField(max_length=20)),
                ('status', models.SmallIntegerField()),
                ('errormessage', models.TextField(blank=True, default=None, null=True)),
                ('submitdate', models.DateTimeField(auto_now_add=True)),
                ('lastdl', models.DateTimeField(blank=True, default=None, null=True)),
                ('pgn', models.TextField(blank=True, default=None, null=True)),
                ('blend', models.BinaryField()),
                ('simulation_duration', models.DurationField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heartbeat', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chessfracture.Worker'),
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('site', 'gameid')},
        ),
    ]
