# Generated by Django 2.1.5 on 2019-01-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessfracture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='black',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='utcdate',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='white',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
