---


- name: install python36
  yum:
    name:
      - python-virtualenv
      - python36
    state: installed
    enablerepo: epel-testing

- name: django venv
  pip:
    virtualenv: "{{django_venv_path}}"
    virtualenv_python: python3.6
    requirements: "/home/{{ chessfracture_user }}/chessfracture/django/requirements.txt"
  become_user: "{{ chessfracture_user }}"

- name: chessfracture-db hosts
  lineinfile:
    path: /etc/hosts
    regexp: chessfracture-db
    line: "{{ hostvars['web'].ansible_default_ipv4.address }} chessfracture-db web"

