---

- name: install blender requirements
  yum:
    name:
      - bzip2
      - mesa-libGLU
      - libXi
      - libXrender
      - xorg-x11-server-Xvfb
      - xorg-x11-utils
      - mesa-dri-drivers
    state: installed

- name: verify if blender archive is present
  stat:
    path: "/home/{{ chessfracture_user }}/blender-2.90.1-linux64.tar.xz"
  register: blender_archive
  become_user: "{{ chessfracture_user }}"

- name: wget blender
  get_url:
    url: https://download.blender.org/release/Blender2.90/blender-2.90.1-linux64.tar.xz
    dest: "/home/{{ chessfracture_user }}/"
  when: blender_archive.stat.exists == false
  become_user: "{{ chessfracture_user }}"

- name: unarchive blender
  unarchive:
    remote_src: yes
    src: "/home/{{ chessfracture_user }}/blender-2.90.1-linux64.tar.xz"
    dest: "/home/{{ chessfracture_user }}/"
    creates: "/home/{{ chessfracture_user }}/blender-2.90.1-linux64"
  become_user: "{{ chessfracture_user }}"

- name: verify if get-pip is present
  stat:
    path: "/home/{{ chessfracture_user }}/blender-2.90.1-linux64/get-pip.py"
  register: get_pip
  become_user: "{{ chessfracture_user }}"

- name: wget get-pip
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: "/home/{{ chessfracture_user }}/blender-2.90.1-linux64/"
  when: get_pip.stat.exists == false
  become_user: "{{ chessfracture_user }}"

- name: install pip
  command: 2.90/python/bin/python3.7m get-pip.py
  args:
    chdir: "/home/{{ chessfracture_user }}/blender-2.90.1-linux64/"
    creates: "/home/{{ chessfracture_user }}/blender-2.90.1-linux64/2.90/python/bin/pip"
  become_user: "{{ chessfracture_user }}"

- name: verify if pip python-chess is installed
  stat:
    path: "/home/{{ chessfracture_user }}/blender-2.90.1-linux64/2.90/python/lib/python3.7/site-packages/chess"
  register: python_chess
  become_user: "{{ chessfracture_user }}"

- name: pip install python-chess
  command: 2.90/python/bin/python3.7m -m pip install python-chess
  args:
    chdir: "/home/{{ chessfracture_user }}/blender-2.90.1-linux64/"
  when: python_chess.stat.exists == false
  become_user: "{{ chessfracture_user }}"

- name: create /tmp/blender
  file:
    path: /tmp/blender
    state: directory
    mode: 0755
    owner: "{{ chessfracture_user }}"
    group: "{{ chessfracture_user }}"

