---

- name: create /etc/sysconfig/systemd/system
  file:
    path: /etc/sysconfig/systemd/system
    state: directory

- name: create systemd service
  template:
    src: etc/systemd/system/chessfracture.worker@.service
    dest: /etc/systemd/system/chessfracture.worker@.service
  notify:
    - systemctl daemon-reload
    - restart chessfracture.worker

- name: start chessfracture.worker
  service:
    name: "chessfracture.worker@{{ item }}"
    enabled: yes
    state: started
  with_sequence: count={{ansible_processor_cores}}
